# Generated by Django 5.0.1 on 2024-06-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default=3, upload_to='images/'),
            preserve_default=False,
        ),
    ]
