# Generated by Django 5.0.1 on 2024-06-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='numbers',
            field=models.IntegerField(default=50, max_length=1000),
        ),
    ]
