# Generated by Django 5.0.1 on 2024-06-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_order_food_remove_order_order_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingletonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.IntegerField(default=50)),
            ],
            options={
                'verbose_name': 'Singleton',
                'verbose_name_plural': 'Singleton',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
